
import fs from 'fs';
import path from 'path';
import { NotebookSessionManager } from '../build/session-manager.js';

const SLEEP_MS = 5000;
const MAX_RETRIES = 60; // 5 minutes max

function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

async function main() {
    try {
        console.log("🚀 Starting K-Culture Research Task...");

        // 1. Load Credentials
        const home = process.env.HOME || process.env.USERPROFILE || "";
        const authPath = path.join(home, ".notebooklm-mcp", "auth.json");

        if (!fs.existsSync(authPath)) {
            console.error("❌ Auth file not found. Please login first.");
            process.exit(1);
        }

        const data = JSON.parse(fs.readFileSync(authPath, "utf-8"));
        const cookieStr = Object.entries(data.cookies || {}).map(([k, v]) => `${k}=${v}`).join("; ");
        const creds = { cookieHeader: cookieStr, csrfToken: data.csrf_token };

        const session = new NotebookSessionManager(creds);

        // Refresh session to get valid CSRF
        try {
            await session.refreshSession();
        } catch (e) {
            console.warn("⚠️ Session refresh warning (continuing might fail):", e.message);
        }

        // 2. Create Notebook
        console.log("Creating new notebook...");
        const project = await session.createNotebookProject("2025 K-Culture Report");
        if (!project) {
            throw new Error("Failed to create notebook project.");
        }
        console.log(`✅ Notebook created: ${project.title} (${project.id})`);

        // 3. Initiate Deep Research
        const topic = "2025년 K-컬처(한류)를 빛낸 10대 인물과 주요 성과 (K-Pop, K-Drama, K-Movie, K-Food 등 포괄)";
        console.log(`🔍 Starting Deep Research on: "${topic}"...`);

        const { taskId } = await session.initiateResearch(project.id, topic, 'deep');
        console.log(`✅ Research started. Task ID: ${taskId}`);

        // 4. Poll for results
        let summary = "";
        let sources = [];

        process.stdout.write("⏳ Researching");
        for (let i = 0; i < MAX_RETRIES; i++) {
            const result = await session.checkResearchStatus(project.id, taskId);

            if (result.status === 'completed') {
                console.log("\n✅ Research completed!");
                summary = result.summary;
                sources = result.sources;

                // Import the findings into the notebook as a source note
                // (Optional but good for history)
                // await session.importResearchResults(project.id, taskId, sources);
                break;
            } else {
                process.stdout.write(".");
                await sleep(SLEEP_MS);
            }
        }

        if (!summary) {
            throw new Error("\n❌ Research timed out or returned empty result.");
        }

        // 5. Generate Report Content
        let reportContent = `# 2025 K-Culture Report: 10 Key Figures\n\n`;
        reportContent += `**Generated by:** NotebookLM MCP Agent\n`;
        reportContent += `**Date:** ${new Date().toLocaleDateString()}\n\n`;
        reportContent += `## Executive Summary\n\n${summary}\n\n`;

        reportContent += `## Sources\n\n`;
        sources.forEach((src, idx) => {
            reportContent += `${idx + 1}. [${src.title || "Source"} (${src.url || "Link"})](${src.url || "#"})\n`;
        });

        // 6. Save to Downloads
        const downloadsPath = path.join(home, 'Downloads', '2025_K_Culture_Report.md');
        fs.writeFileSync(downloadsPath, reportContent, 'utf-8');

        console.log(`\n📄 Report saved to: ${downloadsPath}`);

    } catch (error) {
        console.error("\n❌ Error:", error);
        process.exit(1);
    }
}

main();
